# -*- coding: utf-8 -*
#
# This file is part of CANDrive.
#
# CANDrive is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# CANDrive is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with CANDrive.  If not, see <http://www.gnu.org/licenses/>.

import os

Import(['*'])

SOURCE = Glob('*.c')

env.Append(CPPPATH=[
    '#src/modules/logging',
    '#src/modules/utility',
    '#src/modules/systime',
    '#src/modules/can_interface',
    '#src/modules/isotp',
    '#src/modules/fifo',
    '#src/modules/stream',
    '#src/modules/third_party/memfault/memfault-firmware-sdk/components/include',
    '#src/modules/third_party/memfault'
])

OBJECTS = env.Object(SOURCE)

Return('OBJECTS')
