# -*- coding: utf-8 -*
#
# This file is part of CANDrive.
#
# CANDrive is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# CANDrive is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with CANDrive.  If not, see <http://www.gnu.org/licenses/>.

import os
import subprocess

def get_git_desc():
  return subprocess.Popen('git describe --always --dirty', stdout=subprocess.PIPE, shell=True).stdout.read().strip().decode('utf-8')

Import(['*'])

SOURCE = Glob('*.c')
GIT_DESC = get_git_desc()

env.Append(CPPPATH=[
    '#src/modules/board',
    '#src/modules/logging',
    '#src/modules/serial',
    '#src/modules/systime',
    '#src/modules/image',
    '#src/modules/can_interface',
    '#src/modules/flash',
    '#src/modules/firmware_manager',
    '#src/modules/nvcom'
])

env.Append(CPPDEFINES=['GIT_DESC=\\"{}\\"'.format(GIT_DESC)])

OBJECTS = env.Object(SOURCE)

Return('OBJECTS')
