# -*- coding: utf-8 -*
#
# This file is part of CANDrive.
#
# CANDrive is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# CANDrive is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with CANDrive.  If not, see <http://www.gnu.org/licenses/>.

import os
import subprocess

def get_git_desc():
  return subprocess.Popen('git describe --always --dirty', stdout=subprocess.PIPE, shell=True).stdout.read().strip().decode('utf-8')

Import(['*'])

SOURCE = Glob('*.c')
GIT_DESC = get_git_desc()

env.Append(CPPPATH=[
    '#app/board',
    '#app/utility',
    '#app/logging',
    '#app/can_interface',
    '#app/serial',
    '#app/motor',
    '#app/pwm',
    '#app/adc',
    '#app/systime',
    '#app/motor_controller',
    '#app/console',
    '#app/signal_handler',
    '#app/system_monitor',
    '#app/nvs',
    '#app/config',
    '#app/flash'
])

env.Append(CPPDEFINES=['NAME=\\"CANDriveFw\\"'])

# Clone env to keep the GIT_DESC define in application only.
application_env = env.Clone()
application_env.Append(CPPDEFINES=['GIT_DESC=\\"{}\\"'.format(GIT_DESC)])

OBJECTS = application_env.Object(SOURCE)

Return('OBJECTS')
