# -*- coding: utf-8 -*
#
# This file is part of CANDrive.
#
# CANDrive is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# CANDrive is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with CANDrive.  If not, see <http://www.gnu.org/licenses/>.

import os

Import(['*'])

SOURCE = Glob('*.c')

env.Append(CPPPATH=[
    '#app/board',
    '#app/utility',
    '#app/logging',
    '#app/can_interface',
    '#app/serial',
    '#app/motor',
    '#app/pwm',
    '#app/adc',
    '#app/systime',
    '#app/motor_controller',
    '#app/console',
    '#app/signal_handler',
    '#app/system_monitor'
])

OBJECTS = env.Object(SOURCE)

Return('OBJECTS')
