# -*- coding: utf-8 -*
#
# This file is part of CANDrive.
#
# CANDrive is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# CANDrive is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with CANDrive.  If not, see <http://www.gnu.org/licenses/>.

import os

Import(['*'])

env.Append(CPPPATH=[
    '../test/candb'
])

test_env = env.Clone()
test_env['CCFLAGS'].remove('--coverage')
test_env.Append(CPPPATH=[
    '#app/signal_handler'
    ])

fifo_object = SConscript('#app/fifo/SConscript',
    variant_dir='fifo',
    duplicate=0,
    exports={'env': test_env})

candb_object = SConscript('#app/candb/SConscript',
    variant_dir='candb',
    duplicate=0,
    exports={'env': test_env})

source = Glob('*.c')
objects = test_env.Object(source=source)
test_env.Depends(target = objects, dependency = [candb_object])
objects.append(candb_object)
objects.append(fifo_object)

Return('objects')
